In [10]:
import pandas as pd
X = pd.read_csv(r'train.csv')
x_test = pd.read_csv(r'test.csv')

In [14]:
## Remove rows with missing target, separate target from predictors
X.dropna(axis=0,inplace=True,subset=['SalePrice'])
y = X.SalePrice
X.drop(labels=['SalePrice'],axis=1,inplace=True)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [17]:
# To keep things simple, we'll drop columns with missing values
col_with_missing_values = [col for col in X.columns if X[col].isnull().any()]
X.drop(col_with_missing_values,axis=1,inplace=True)
x_test.drop(col_with_missing_values,axis=1,inplace=True)

In [18]:
X.isnull().sum()

Id               0
MSSubClass       0
MSZoning         0
LotArea          0
Street           0
                ..
MiscVal          0
MoSold           0
YrSold           0
SaleType         0
SaleCondition    0
Length: 61, dtype: int64